create table day (id int4 generated by default as identity, date date not null, afternoon_engergy varchar(255), evening_engergy varchar(255), morning_engergy varchar(255), social varchar(255), work varchar(255), primary key (id))
create table meal (id int4 generated by default as identity, amount int4, carbs int4, consumation_time timestamp not null, day int4, primary key (id))
create table nutrient (id int4 generated by default as identity, amount int4, type varchar(255), meal int4, primary key (id))
alter table if exists meal add constraint FK_meal_to_day foreign key (day) references day
alter table if exists nutrient add constraint FK_nutrient_to_meal foreign key (meal) references meal
